PROYECTO FINAL

Diaz Gaston Alejandro - DNI: 32016726

1.- Introducción

Debo expresar que todo lo que continue se expresara a modo hipótetico debido a que nada de lo que se exprese sera real, ya que en el desarrollo de este trabajo se utilizó un dataset obtenido de forma gratuita desde la plataforma web de Kaggle, desde el siguiente link https://www.kaggle.com/datasets/muhammadehsan000/healthcare-dataset-2019-2024 con datos sobre la atencion Médica desde 2019 a 2024. La idea es poder demostrar las habilidades obtenidas de la realizacion del bootcamp de Ciencia de Datos de la 4ta generacion de codigofacilito.

2.- Conociendo el Dataset

In [87]:
#Librerias básica para el analisis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [89]:
# Cargando los datos del CSV en un Dataframe
df_1 = pd.read_csv("C:/Users/GASTON/Desktop/Proyecto/ProjectDiazGaston/healthcare_dataset.csv", sep = ",")
# Trabajare los datos en una copia
df_health = df_1.copy()

In [91]:
#Dimension del dataset
print(df_health.shape)

(55500, 15)

In [93]:
df_health.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [95]:
#Tipo de dato para cada columna
df_health.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

Información del conjunto de datos:
El conjunto de datostienes15  columna y 55500 registros,, cadacolumnas proporciona detalles específicos sobre los pacientes, sus admisiones y los servicios de atención médica recibidos.muchas estan en tipo object que mas tarde trabajaremos, pero antes a modo de indice y consulta harea una breve descripción de cada columna:

NamNombre del paciente.rd.
AEdad del paciente al momento del ingresoears.
GenGénero del paciente.ale."
Blood Tipo de sangre del paciente "O-").
Medical CondCondición o diagnóstico médico primarionsion").
Date of AdmFecha de ingreso del paciente al centro de salud.acility.Nombre del médico que le da ingresoadmission.
Centro de salud u hospital donde ingresó el paciente. admitted.
Insurance Provider: Patient’s insurance provider (e.g., "Aetna," "Blue Cross").
BillMutual o Prepaga que cubre la atencion medica.oint number.
Número de habitación donde se alojó el paciente.accommodated.
AdTipo de admisión or "Urgent").
DFecha de alta del centro de atención médicac range of dayMedicamentos recetados o administrados," "Ibuprofen")Resultados de las pruebas médicas durante el ingreso ("Normal", "Anormal", "No concluyente").oncluyente"). "Inconclusive").

In [98]:
#Veamos las primeras 6 filas
df_health.head(6)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
5,EMILY JOHNSOn,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal

In [100]:
#Veamos las 5 ultimas filas
df_health.tail(6)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55494,JEssIcA WHiTe,67,Male,O+,Arthritis,2023-12-11,Jesus Jordan,Miller-Harris,Medicare,42535.301234,378,Emergency,2024-01-04,Ibuprofen,Normal
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [102]:
#Reviso si hay nulos. 
df_health.count()

Name                  55500
Age                   55500
Gender                55500
Blood Type            55500
Medical Condition     55500
Date of Admission     55500
Doctor                55500
Hospital              55500
Insurance Provider    55500
Billing Amount        55500
Room Number           55500
Admission Type        55500
Discharge Date        55500
Medication            55500
Test Results          55500
dtype: int64

In [ ]:
#---Data Wrangling (Aca comenzare a manipular los datos)---

In [106]:
#Tipo de dato para cada columna
df_health.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [108]:
#Borrare el Atributo nombre, la intencion es no individualizar al paciente. 
df_health = df_health.drop(labels='Name', axis=1)

In [110]:
#Cambiare a 0 los masculinos y 1 los femeninos
df_health['Gender'] = df_health['Gender'].map({'Male': 0, 'Female': 1}).astype(int)

In [120]:
#Convierto variable de tipo object en datetime
df_health['Date of Admission'] = pd.to_datetime(df_health['Date of Admission'])

In [126]:
#Convierto variable de tipo object en datetime
df_health['Discharge Date'] = pd.to_datetime(df_health['Discharge Date'])

In [130]:
df_health['day difference'] = df_health['Discharge Date'] - df_health['Date of Admission']

AttributeError: module 'pandas' has no attribute 'to_int'

In [134]:
df_health.head(6)

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,day difference
0,30,0,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2 days
1,62,0,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6 days
2,76,1,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15 days
3,28,1,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30 days
4,43,1,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20 days
5,36,0,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal,4 days

In [ ]:
correlacion = df_health.corr(method="pearson")
correlacion.head()

In [45]:
conda install panda_profiling

Collecting package metadata (current_repodata.json): ...working... done
Note: you may need to restart the kernel to use updated packages.

Solving environment: ...working... unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

Error while loading conda entry point: anaconda-cloud-auth (cannot import name 'ChannelAuthBase' from 'conda.plugins.types' (C:\Users\GASTON\anaconda3\Lib\site-packages\conda\plugins\types.py))
Error while loading conda entry point: anaconda-cloud-auth (cannot import name 'ChannelAuthBase' from 'conda.plugins.types' (C:\Users\GASTON\anaconda3\Lib\site-packages\conda\plugins\types.py))

PackagesNotFoundError: The following packages are not available from current channels:

  - panda_profiling

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

In [ ]:
from pandas_profiling